### PR TITLE
newlib: Pull in Xtensa malloc failure workaround

### PR DESCRIPTION
**Pull request by stephanosio**
```
Pull in the newlib workaround for the Xtensa malloc failure issue
reported in zephyrproject-rtos/zephyr#38258.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
```

Zephyr newlib PR: https://github.com/zephyrproject-rtos/newlib-cygwin/pull/5

### CODE REVIEW

**Comment by stephanosio** [comment]
Verified working:
```
*** Booting Zephyr OS build zephyr-v2.6.0-2928-g296cecd30943  ***
_sbrk: 0x60004f68, 152
_sbrk: 0x60005000, 0
000: 0x60004f70
_sbrk: 0x60005000, 4096
001: 0x60004ff8
002: 0x60005080
003: 0x60005108
004: 0x60005190
005: 0x60005218
006: 0x600052a0
007: 0x60005328
008: 0x600053b0
009: 0x60005438
010: 0x600054c0
011: 0x60005548
012: 0x600055d0
013: 0x60005658
014: 0x600056e0
015: 0x60005768
016: 0x600057f0
017: 0x60005878
018: 0x60005900
019: 0x60005988
020: 0x60005a10
021: 0x60005a98
022: 0x60005b20
023: 0x60005ba8
024: 0x60005c30
025: 0x60005cb8
026: 0x60005d40
027: 0x60005dc8
028: 0x60005e50
029: 0x60005ed8
030: 0x60005f60
_sbrk: 0x60006000, 4096
031: 0x60005fe8
032: 0x60006070
033: 0x600060f8
```

Note that the first malloc no longer returns `NULL`.

Tested with https://github.com/stephanosio/zephyr/commits/reproduce_38258_sdkpr394

**Comment by galak** [comment]
@dcpleung do you mind looking at the newlib change here:

https://github.com/zephyrproject-rtos/newlib-cygwin/pull/5

**Comment by galak** [comment]
@sylvioalves any concerns here on the newlib change:

zephyrproject-rtos/newlib-cygwin#5

**Comment by sylvioalves** [comment]
> @sylvioalves any concerns here on the newlib change:
> 
> [zephyrproject-rtos/newlib-cygwin#5](https://github.com/zephyrproject-rtos/newlib-cygwin/pull/5)

@stephanosio @galak I tested same `hello_world` sample provided and it worked without any issues. However, by the address diff below, you see 2-extra bytes in between consecutive values.  
I am using custom esp32 toolchain using zephyr's newlib repo and gcc/gdb/binutils from Espressif. I'll test changing the MALLOC_ALIGNMENT to 8 as well. For now:
```c
*** Booting Zephyr OS build v2.7.0-rc1-35-ga3c19caad61c  ***
000: 0x3ffb0f60
001: 0x3ffb0ff0
002: 0x3ffb1080
003: 0x3ffb1110
004: 0x3ffb11a0
005: 0x3ffb1230
006: 0x3ffb12c0
007: 0x3ffb1350
008: 0x3ffb13e0
009: 0x3ffb1470
010: 0x3ffb1500
011: 0x3ffb1590
012: 0x3ffb1620
013: 0x3ffb16b0
014: 0x3ffb1740
015: 0x3ffb17d0
016: 0x3ffb1860
017: 0x3ffb18f0
018: 0x3ffb1980
019: 0x3ffb1a10
020: 0x3ffb1aa0
021: 0x3ffb1b30
022: 0x3ffb1bc0
023: 0x3ffb1c50
024: 0x3ffb1ce0
025: 0x3ffb1d70
026: 0x3ffb1e00
027: 0x3ffb1e90
028: 0x3ffb1f20
029: 0x3ffb1fb0
030: 0x3ffb2040
031: 0x3ffb20d0
032: 0x3ffb2160
033: 0x3ffb21f0
```

**Comment by sylvioalves** [comment]
After changing the toolchain with that `MALLOC_ALIGNMENT` removed, i.e., making default to 8, it also works without any issue. The extra 2-byte is now removed and result is very similiar to the qemu test (without allocation failure). Any comments?

```c
�*** Booting Zephyr OS build v2.7.0-rc1-35-ga3c19caad61c  ***
000: 0x3ffb0f60
001: 0x3ffb0fe8
002: 0x3ffb1070
003: 0x3ffb10f8
004: 0x3ffb1180
005: 0x3ffb1208
006: 0x3ffb1290
007: 0x3ffb1318
008: 0x3ffb13a0
009: 0x3ffb1428
010: 0x3ffb14b0
011: 0x3ffb1538
012: 0x3ffb15c0
013: 0x3ffb1648
014: 0x3ffb16d0
015: 0x3ffb1758
016: 0x3ffb17e0
017: 0x3ffb1868
018: 0x3ffb18f0
019: 0x3ffb1978
020: 0x3ffb1a00
021: 0x3ffb1a88
022: 0x3ffb1b10
023: 0x3ffb1b98
024: 0x3ffb1c20
025: 0x3ffb1ca8
026: 0x3ffb1d30
027: 0x3ffb1db8
028: 0x3ffb1e40
029: 0x3ffb1ec8
030: 0x3ffb1f50
031: 0x3ffb1fd8
032: 0x3ffb2060
033: 0x3ffb20e8
```

**Review by galak — APPROVED** [review]

**Pull request merged**
