### PR TITLE
qemu: Add patches to support booting qemu_cortex_m4

### PR DESCRIPTION
**Pull request by stephanosio**
This commit adds the patches that are required to support booting the
`qemu_cortex_m4` platform, which uses the Netduino Plus 2 target based
on the STM32F405 SoC emulation.

For more details, refer to the commit message in each patch.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

~~To be rebased once #200 is merged~~

### CODE REVIEW

**Comment by stephanosio** [comment]
Blocked by #200

**Comment by galak** [comment]
What's the status of these patches w/regards to upstream qemu?

	   file://0001-hw-core-Support-device-reset-handler-priority.patch \
	   file://0002-hw-arm-armv7m-Downgrade-CPU-reset-handler-priority.patch \
	   file://0003-hw-arm-stm32f405-Add-preliminary-RCC-emulation-suppo.patch \
	   file://0004-hw-arm-stm32f405-Add-preliminary-flash-interface-emu.patch \

**Comment by stephanosio** [comment]
>    file://0001-hw-core-Support-device-reset-handler-priority.patch \
>    file://0002-hw-arm-armv7m-Downgrade-CPU-reset-handler-priority.patch \

These two patches probably will not be accepted (it is the last resort). They are planning to rework the reset API and the problem should be taken care of once they do that.

**Comment by stephanosio** [comment]
>    file://0003-hw-arm-stm32f405-Add-preliminary-RCC-emulation-suppo.patch \
>    file://0004-hw-arm-stm32f405-Add-preliminary-flash-interface-emu.patch \

I still need to send v2 for these, haven't really got around doing that. I will probably do that later when I have some time to spare.

https://patchwork.kernel.org/patch/11413857/
https://patchwork.kernel.org/patch/11414187/

**Comment by stephanosio** [comment]
Rebased

**Comment by galak** [comment]
Can you rebase since I merged the arc icount pr there is a merge conflict.

**Comment by stephanosio** [comment]
Rebased

**Comment by stephanosio** [comment]
Build failure is due to source code download failure during crosstool-ng build process and can be safely ignored.

**Comment by stephanosio** [comment]
Abandoning this work for now because the ARM hard FP testing in the CI, which was the primary goal of this, is now covered by another platform (ARMv8-M).

Nevertheless, ARMv7-M FP testing is not currently covered and it would still be meaningful to add this in the future.

**Pull request closed without merging**
