### PR TITLE
gcc: ARC changes to add missing rel310a mcpu

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
NOTE: this PR for test only - we use local fork of zephyrproject-rtos/gcc with changes which haven't picked yet to zephyrproject-rtos repos.

### CODE REVIEW

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/gcc/pull/10 has been merged.

**Comment by stephanosio** [comment]
@evgeniy-paltsev Is this ready? If so, can you please mark it "ready for review?"

**Review by abrodkin — APPROVED** [review]

**Comment by stephanosio** [comment]
Due to lack of response, will be merged as part of https://github.com/zephyrproject-rtos/sdk-ng/pull/559.

**Comment by evgeniy-paltsev** [comment]
> will be merged as part of https://github.com/zephyrproject-rtos/sdk-ng/pull/559.

Yep, that's totally OK, thanks!

**Pull request closed without merging**
