### PR TITLE
gcc: enable big-endian toolchain for armv7-R

### PR DESCRIPTION
**Pull request by ntavish**

### CODE REVIEW

**Comment by ntavish** [comment]
Hi @stephanosio thanks for re-triggering the CI. I am trying to find the downloads for build#2, but I can't find them, can you tell me where they are?
Also, what would be required to get this merged? I can do some basic testing, but unfortunately I don't have a working port for a cortex-r5 big-endian with zephyr main branch right now. I am planning to start working on adding support for TMS570 upstream, and this is required for that.

**Comment by sigmundklaa** [comment]
@ntavish If you are interested, I have done some work for supporting TMS570LS1224 at https://github.com/OrbitNTNU/zephyr-hw. I have been planning to push it to upstream, if I ever end up finishing it. Let me know if you would like to collaborate!

**Comment by rahul-arasikere** [comment]
I too have been looking to working on a port of RM57Lx series here on a best effort basis: https://github.com/rahul-arasikere/zephyr/tree/add-rm57lx-support. Haven't done enough of a port to start testing however.

**Comment by stephanosio** [comment]
Rebased and updated gcc sha.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
