### PR TITLE
qemu: backport some pmp riscv fixes from upstream

### LINKED ISSUE #277: add Riscv PMP hotfix to QEMU 5.1.0
This is in QEMYU's upstream master branch, but staged for 5.2.

The patch is small:
https://github.com/zephyrproject-rtos/zephyr/files/4960922/0002-riscv-pmp-granularity-hotfix.patch.txt

Please pull this into the QEMU build for the 0.12 SDK release, so we can get CI coverage of https://github.com/zephyrproject-rtos/zephyr/pull/27063 and memory protection on Risc V.

### PR DESCRIPTION
**Pull request by galak**
Pull in some fixes related to PMP support on RISCV from upstream qemu

Fixes #277

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
Link to full SDK:

http://builds.zephyrproject.org/zephyrproject-rtos/sdk-ng/279/zephyr-sdk-0.12.0-alpha-1-pr-279-x86_64-linux-setup.run

**Comment by galak** [comment]
hosttools which includes QEMU:
https://builds.zephyrproject.org/zephyrproject-rtos/sdk-ng/279/zephyr-sdk-x86_64-hosttools-standalone-0.9.sh

**Comment by amergnat** [comment]
Hello @galak 
I test the QEMU of this alpha SDK build on my PR with success for now (I need to fix some test to validate all sanity)
https://github.com/zephyrproject-rtos/zephyr/pull/27063#issuecomment-712138880

**Comment by galak** [comment]
> Hello @galak
> I test the QEMU of this alpha SDK build on my PR with success for now (I need to fix some test to validate all sanity)
> More details of the test here:
> [zephyrproject-rtos/zephyr#27063 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/27063#issuecomment-712138880)

thanks, will merge this to be part of the 0.12.0 sdk release.

**Comment by galak** [comment]
Thanks for the fix.

**Pull request merged**
