### PR TITLE
xtensa: Add nxp_rt600_adsp toolchain

### PR DESCRIPTION
**Pull request by VitekST**
This PR adds a toolchain configuration file and overlay for the HiFi 4 DSP instantiated on NXP's MIMXRT685. Added files were taken from "nxp_rt600_RI23_11_newlib_linux.tgz" available from https://tensilicatools.com.

An SoC overlay in hal_xtensa is related to this: https://github.com/zephyrproject-rtos/hal_xtensa/pull/26

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@nashif @stephanosio @keith-packard @dcpleung can you, please, review.

**Review by iuliana-prodan — APPROVED** [review]

**Comment by dbaluta** [comment]
Please add this info:

image

to commit message. People will read git log more often than look PRs on github.

**Review by dcpleung — APPROVED** [review]
LGTM.

Regarding GDB, maybe the register map is incorrect?

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
Ready to merge.

**Review by dbaluta — APPROVED** [review]

**Comment by VitekST** [comment]
> LGTM.
> 
> Regarding GDB, maybe the register map is incorrect?

@dcpleung It's actually the GDB server I use for debugging (J-Link GDB Server V7.90) not supporting the `g` GDB packet (read all registers). Looks like `xt-gdb` does not issue those packets and instead issues `p` packets for reading each known register individually. I tried modifying GDB to send those instead, and, well, it connects, but shows bogus addresses and drives the target into a double exception. It needs work which is pretty far above my knowledge base. If you could point me somewhere else, I would be more than grateful.

**Comment by dcpleung** [comment]
> > LGTM.
> > Regarding GDB, maybe the register map is incorrect?
> 
> @dcpleung It's actually the GDB server I use for debugging (J-Link GDB Server V7.90) not supporting the `g` GDB packet (read all registers). Looks like `xt-gdb` does not issue those packets and instead issues `p` packets for reading each known register individually. I tried modifying GDB to send those instead, and, well, it connects, but shows bogus addresses and drives the target into a double exception. It needs work which is pretty far above my knowledge base. If you could point me somewhere else, I would be more than grateful.

In that case, try adding `CT_GDB_CROSS_EXTRA_CONFIG_ARRAY="--enable-xtensa-use-target-regnum --disable-xtensa-remote-g-packet"` to the config file. This should make it work with xt-gdb (though not sure about J-Link).

**Review by dcpleung — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by dbaluta** [comment]
@stephanosio any update on the next SDK release that will inculde rt600 toolchain?

**Comment by dbaluta** [comment]
@stephanosio can you please help with a new SDK release to include this toolchain?

**Comment by stephanosio** [comment]
> @stephanosio can you please help with a new SDK release to include this toolchain?

I will look into releasing a new SDK version in February alongside other changes.

**Comment by dbaluta** [comment]
@stephanosio @dleach02 if you need help with sdk-ng I can temporarily help for this release. Just let me know. Would be nice to have this release sooner than February!

**Pull request merged**
