### PR TITLE
openocd: fix issue on ARC based systems

### LINKED ISSUE #65: arc emsk's openocd debugger doesn't work in Zephyr SDK 0.9.5
**Describe the bug**
After Zephyr SDK updated to 0.9.5,  the openocd debugger of arc em_starterkit doesn't work correctly.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=em_starterkit_em7d ..
3. make
4. west debug
5. see error

**Expected behavior**
the debugger cann't run because of error caused by openocd.

**Impact**
can't debug the em_starterkit hardware

**Screenshots or console output**
The log is as follow:

Using runner: em-starterkit
Open On-Chip Debugger 0.10.0+dev-gea2753a7-dirty (2018-11-02-23:37)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 5000 kHz
Info : clock speed 5000 kHz
Info : JTAG tap: arc-em.cpu tap/device found: 0x200044b1 (mfg: 0x258 (ARC International), part: 0x0004, ver: 0x2)
**Register `identity' is not found.**
in procedure 'init' 
in procedure 'ocd_bouncer'

Info : Listening on port 3333 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* arc-em.cpu         arcv2      little arc-em.cpu         halted
Info : Listening on port 6333 for tcl connections
Info : Listening on port 4444 for telnet connections
GNU gdb (GDB) 7.12.0.20161010-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pokysdk-linux --target=arc-zephyr-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/wren/zephyr/samples/philosophers/emsk/zephyr/zephyr.elf...done.
Info : accepting 'gdb' connection on tcp/3333
Remote debugging using :3333
warning: while parsing target description (at line 6): Boolean fields must be one bit in size
**warning: Could not load XML target description; ignoring
openocd: src/server/gdb_server.c:1188: gdb_get_registers_packet: Assertion `reg_packet_size > 0' failed.
Remote connection closed**

**Environment (please complete the following information):**
 - OS: Linux/Debian
 - Toolchain (Zephyr SDK)
 - latest commit

**Additional context**

### PR DESCRIPTION
**Pull request by nashif**
This fixes issues with ARC based systems and adds 2 patches addressing
the problem.

Fixes #65

### CODE REVIEW

**Comment by abrodkin** [comment]
@nashif I'm wondering if this issue is blocking any release? I.e. how much time do I have to properly implement http://openocd.zylin.com/#/c/5160/?

**Comment by galak** [comment]
> @nashif I'm wondering if this issue is blocking any release? I.e. how much time do I have to properly implement [http://openocd.zylin.com/#/c/5160](http://openocd.zylin.com/#/c/5160/)?

Sooner than later.

**Comment by galak** [comment]
Closing this now til we get an updated gdb patch for ARC openocd.

**Comment by abrodkin** [comment]
@galak @sstallion @nashif posted a new version here: http://openocd.zylin.com/#/c/5179/
Sorry for not updating previous version - it's been a long time since I used Gerrit and so didn't manage to do everything right.

**Comment by galak** [comment]
> @galak @sstallion @nashif posted a new version here: http://openocd.zylin.com/#/c/5179/
> Sorry for not updating previous version - it's been a long time since I used Gerrit and so didn't manage to do everything right.

@abrodkin any update on the upstream change?

**Comment by abrodkin** [comment]
@galak just pushed my v2

**Comment by galak** [comment]
> @galak just pushed my v2

Any update?

**Comment by abrodkin** [comment]
@galak no ideas, I'd say somebody from OpenOC Dmaintainers is supposed to cherry-pick my change from http://openocd.zylin.com/#/c/5179/ as there's no request for changes etc.

**Comment by galak** [comment]
> @galak no ideas, I'd say somebody from OpenOC Dmaintainers is supposed to cherry-pick my change from [http://openocd.zylin.com/#/c/5179](http://openocd.zylin.com/#/c/5179/) as there's no request for changes etc.

Is http://openocd.zylin.com/#/c/5160/ need or just 5179?

**Comment by abrodkin** [comment]
Only http://openocd.zylin.com/#/c/5179 as it's a re-spin of initially proposed 5160.
I dropped "Change-Id" on pushing v2 and that's how it ended-up as a separate Gerrit item.

**Comment by galak** [comment]
> Only http://openocd.zylin.com/#/c/5179 as it's a re-spin of initially proposed 5160.
> I dropped "Change-Id" on pushing v2 and that's how it ended-up as a separate Gerrit item.

ok, can you close 5160.  Do you mind sending a PR to https://github.com/zephyrproject-rtos/openocd with the 5179 change?

**Comment by abrodkin** [comment]
@galak done, see https://github.com/zephyrproject-rtos/openocd/pull/9

**Comment by galak** [comment]
Thanks. merged in and opened https://github.com/zephyrproject-rtos/sdk-ng/pull/79

**Pull request closed without merging**
