### PR TITLE
Gdb 9.2

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@dcpleung can I get you to look at porting the xtensa GDB patches to GDB 9.1:

```
commit 9c2435319e35df2a7580fce84de9e39f9ac21175
Author: Daniel Leung <daniel.leung@intel.com>
Date:   Wed Feb 26 22:22:09 2020 -0800

    xtensa: intel_s1000: update to GDB 8.3.1
```

**Comment by dcpleung** [comment]
> @dcpleung can I get you to look at porting the xtensa GDB patches to GDB 9.1:
> 
> ```
> commit 9c2435319e35df2a7580fce84de9e39f9ac21175
> Author: Daniel Leung <daniel.leung@intel.com>
> Date:   Wed Feb 26 22:22:09 2020 -0800
> 
>     xtensa: intel_s1000: update to GDB 8.3.1
> ```

Let me take a look. Hopefully it won't be too complicated.

**Comment by dcpleung** [comment]
The updated patch files can be found in https://github.com/dcpleung/sdk-ng/tree/xtensa_gdb_9_2
I have tested it on `intel_s1000_crb` and I was able to read registers.

**Comment by galak** [comment]
> The updated patch files can be found in https://github.com/dcpleung/sdk-ng/tree/xtensa_gdb_9_2
> I have tested it on `intel_s1000_crb` and I was able to read registers.

thanks, pulled in those changes.

**Pull request merged**
