### PR TITLE
Zephyr ctng

### PR DESCRIPTION
**Pull request by galak**
Move to using a zephyr fork of crosstool-ng.

### CODE REVIEW

**Comment by stephanosio** [comment]
@galak Can we transfer https://github.com/stephanosio/zephyr-crosstool-ng repo to zephyrproject-rtos and use it, so that we can keep all the issues as well as the changes there?

**Comment by galak** [comment]
> @galak Can we transfer https://github.com/stephanosio/zephyr-crosstool-ng repo to zephyrproject-rtos and use it, so that we can keep all the issues as well as the changes there?

We can, I'm fine with doing that, just would ask we have your changes on a branch and "re-submit" them as PRs to the master branch to go through a review cycle.

**Comment by abrodkin** [comment]
@stephanosio @galak not sure if that's the right place for asking these questions but I'll try:
1. I may understand why Zephyr uses forks instead of upstream projects as they are. I guess the major reason is here in Zephyr we move so fast that we don't want to wait for upstream projects to accept required changes. But... is there a plan really to contribute Zephyr changes back to upstream? Obviously if not all but some changes are perfectly applicable to the upstream project and should be integrated there. And sooner the better. Otherwise we may find ourselves here being so far from upstream origin so that it won't be even practical about cherry-picking anything to upstream projects which was left so far behind. In case of CT-NG it seems like there're users of upstream project like Xilinx (see https://static.sched.com/hosted_files/ossna2020/19/ELC-Yocto-Crosstool-ng.pdf), we at Synopsys (see https://github.com/foss-for-synopsys-dwc-arc-processors/crosstool-ng) and most probably quite some more given 400+ forks (https://github.com/crosstool-ng/crosstool-ng/network/members).

2. Is there a plan to move QEMU building from way too complicated OpenEmbedded to CT-NG?

3. I noticed that all CT-NG builds seem to be done in a "native" fashion, i.e. Window sflavor gets built on Windows, macOS tools are being built on mac. Knowing there're problems with building on Mac (eve see http://crosstool-ng.github.io/2018/11/26/macos.html) and some inconvenience in building on Windows why don't we build everything on Linux in a cross-compilation (or rather cross-canadian) style? For that MinGW is easily available for Windows builds and osxcross (https://github.com/tpoechtrager/osxcross) for mac. It all might be bundled in the one and only container and used for building of everything. See https://github.com/multiarch/crossbuild as something very close to our needs (sans GCC built for mac but it could be easily done).

**Comment by stephanosio** [comment]
> 1. I may understand why Zephyr uses forks instead of upstream projects as they are. I guess the major reason is here in Zephyr we move so fast that we don't want to wait for upstream projects to accept required changes. But... is there a plan really to contribute Zephyr changes back to upstream?

I think the main issue is that the upstream crosstool-ng repository is not vigorously maintained (reviews are very slow if any, and as you can see, there has been no commit to the master branch since April 2020, and no new tag/release since Apr 2019).

> 2\. Is there a plan to move QEMU building from way too complicated OpenEmbedded to CT-NG?

We will eventually need to drop Yocto/OE (and potentially sdk-ng as whole) in order to provide a cross-platform SDK anyway. See https://github.com/zephyrproject-rtos/zephyr/pull/25475#issuecomment-645731557

> 3\. I noticed that all CT-NG builds seem to be done in a "native" fashion, i.e. Window sflavor gets built on Windows, macOS tools are being built on mac. Knowing there're problems with building on Mac (eve see http://crosstool-ng.github.io/2018/11/26/macos.html) and some inconvenience in building on Windows why don't we build everything on Linux in a cross-compilation (or rather cross-canadian) style? For that MinGW is easily available for Windows builds and osxcross (https://github.com/tpoechtrager/osxcross) for mac. It all might be bundled in the one and only container and used for building of everything. See https://github.com/multiarch/crossbuild as something very close to our needs (sans GCC built for mac but it could be easily done).

[My fork](https://github.com/stephanosio/zephyr-crosstool-ng) already builds (Canadian cross compiles) Windows tools on Linux and, of courses, Linux tools on Linux. As for macOS, Canadian cross compilation from Linux does not seem to be possible (or at least, in a practical sense while keeping things sane).

I wish I had more time to look into this, but I am currently occupied with other more imminent tasks. I do plan to eventually get back to this though ...

**Comment by abrodkin** [comment]
> > 1. I may understand why Zephyr uses forks instead of upstream projects as they are. I guess the major reason is here in Zephyr we move so fast that we don't want to wait for upstream projects to accept required changes. But... is there a plan really to contribute Zephyr changes back to upstream?
> 
> I think the main issue is that the upstream crosstool-ng repository is not vigorously maintained (reviews are very slow if any, and as you can see, there has been no commit to the master branch since April 2020, and no new tag/release since Apr 2019).

That's right. But... there seems to be not enough push for either release or any significant changes. People just added small bits of fixes here and there (and among others I've been doing the same :). It might make sense to reach out to @stilor and discuss co-maintaining or even taking over maintenance. CT-NG has a history of changing hands already as you might know :)
 
> > 2. Is there a plan to move QEMU building from way too complicated OpenEmbedded to CT-NG?
> 
> We will eventually need to drop Yocto/OE (and potentially sdk-ng as whole) in order to provide a cross-platform SDK anyway. See [zephyrproject-rtos/zephyr#25475 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/25475#issuecomment-645731557)

Ok, good I remember this thread.

> > 3. I noticed that all CT-NG builds seem to be done in a "native" fashion, i.e. Window sflavor gets built on Windows, macOS tools are being built on mac. Knowing there're problems with building on Mac (eve see http://crosstool-ng.github.io/2018/11/26/macos.html) and some inconvenience in building on Windows why don't we build everything on Linux in a cross-compilation (or rather cross-canadian) style? For that MinGW is easily available for Windows builds and osxcross (https://github.com/tpoechtrager/osxcross) for mac. It all might be bundled in the one and only container and used for building of everything. See https://github.com/multiarch/crossbuild as something very close to our needs (sans GCC built for mac but it could be easily done).
> 
> [My fork](https://github.com/stephanosio/zephyr-crosstool-ng) already builds (Canadian cross compiles) Windows tools on Linux and, of courses, Linux tools on Linux. As for macOS, Canadian cross compilation from Linux does not seem to be possible (or at least, in a practical sense while keeping things sane).
> 
> I wish I had more time to look into this, but I am currently occupied with other more imminent tasks. I do plan to eventually get back to this though ...

Well as I just very recently learned with help of aforementioned `osxcross` it's possible to build a pretty sane cross-toolchain for mac and then use it with CT-NG. Here https://gist.github.com/abrodkin/12e5c25d97a3969ed5ad6c99e3c7d824 I put down a step-by-step guide (initially for my future use). Once that funky procedure is wrapped into the Dockerfile & container image it will be as easily usable as native Linux tools. I might help here if there's any interest.

**Pull request closed without merging**
