### PR TITLE
xtensa: remove HAL from SDK build

### PR DESCRIPTION
**Pull request by lgirdwood**
The xtensa HAL module should be used instead of the SDK HAL so
remove it. This also fixes some build time confusion between headers
and HAL linkage.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@nashif @dcpleung @galak fyi

**Comment by dcpleung** [comment]
You can remove the patches under `patches/xtensa/hal/*`.

**Comment by lgirdwood** [comment]
Patches now removed. Btw, should there be a codeowners for the SDK ? Seems we have to manually add reviewers.

**Comment by jhedberg** [comment]
@galak are you fine with this now?

**Comment by galak** [comment]
@nashif @dcpleung @lgirdwood what's the implication of this change?  I'm fine with it, just trying to figure out if this is a 0.12.0 kinda thing or 0.11.3.  Ie will zephyr 2.2 build with this change w/o any modifications?

**Comment by dcpleung** [comment]
@galak This requires https://github.com/zephyrproject-rtos/zephyr/pull/23142 and an update to `west.yml` to point to the latest HAL commit. Both `qemu_xtensa` and `intel_s1000_crb` should be good to go as I was testing GDB without building the HAL in SDK.

**Comment by jhedberg** [comment]
Any chance of getting this PR moving forward?

**Comment by galak** [comment]
> Any chance of getting this PR moving forward?

this is a breaking change for the SDK so it would mean SDK 0.12.x.

There are a few items that need possibly figuring out:
1. Do we want any other releases on the 0.11.x line of development (right now I think the CI / release process for SDK can't handle branches well)
2. For SDK 0.12.x I'd update all tools -- there is some time sync issues with QEMU 5.x and openocd (updated ARC support).
3. bandwidth to work on all of that.

**Comment by dcpleung** [comment]
The bootloader for `up_squared_adsp` won't build on `zephyr-v2.2.0` without the HAL in SDK, but this issue is fixed on master.

On current master, all platforms requiring the HAL can be built with the Xtensa HAL module, and the HAL in SDK can be removed.

**Pull request merged**
