### PR TITLE
arc: Use register 26 for TLS storage.

### PR DESCRIPTION
**Pull request by keith-packard**
Include gcc version with change that specifies default tp-regno for arc target so that the whole toolchain will agree.

Signed-off-by: Keith Packard <keithp@keithp.com>

### CODE REVIEW

**Comment by stephanosio** [comment]
DNM until https://github.com/zephyrproject-rtos/gcc/pull/17 is merged

**Comment by stephanosio** [comment]
For the SDK 0.15.2 release, we will stick with the approach @evgeniy-paltsev prefers: https://github.com/zephyrproject-rtos/sdk-ng/pull/595#issue-1452776237

**Comment by keith-packard** [comment]
> For the SDK 0.15.2 release, we will stick with the approach @evgeniy-paltsev prefers: [#595 (comment)](https://github.com/zephyrproject-rtos/sdk-ng/pull/595#issue-1452776237)

Whatever they prefer is fine, of course.

**Comment by keith-packard** [comment]
It sounds like this isn't being revisited for the 0.16 SDK work; shall we close this PR?

**Comment by stephanosio** [comment]
Closing for now.

**Pull request closed without merging**
