### PR TITLE
xtensa: nxp_imx8ulp_adsp: Add missing include header

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Add missing header to fix imx8ulp_adsp toolchain.

Fixes: e88c208e53a6 ("xtensa: Add 8ulp_adsp toolchain")

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@nashif  @dcpleung @keith-packard @tejlmand @dbaluta @dleach02 Please review this
Thanks!

**Review by dcpleung — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
I don't understand why some CI tests are failing (they are, definitely, not related with this fix) so I did an amend just to retrigger the CI.

**Comment by stephanosio** [comment]
> I don't understand why some CI tests are failing (they are, definitely, not related with this fix) so I did an amend just to retrigger the CI.

```
ERROR   - platform_filter - unrecognized platform - qemu_xtensa_mmu
```

It looks like the `qemu_xtensa_mmu` platform, which is required by the SDK CI, has been either renamed or removed from Zephyr. I will look into fixing this.

**Comment by iuliana-prodan** [comment]
> > I don't understand why some CI tests are failing (they are, definitely, not related with this fix) so I did an amend just to retrigger the CI.
> 
> ```
> ERROR   - platform_filter - unrecognized platform - qemu_xtensa_mmu
> ```
> 
> It looks like the `qemu_xtensa_mmu` platform, which is required by the SDK CI, has been either renamed or removed from Zephyr. I will look into fixing this.

Thanks!
I thought it might be related with this: https://github.com/zephyrproject-rtos/zephyr/pull/64464, but I did a rebase on Friday and still failing.

**Comment by dcpleung** [comment]
> > I don't understand why some CI tests are failing (they are, definitely, not related with this fix) so I did an amend just to retrigger the CI.
> 
> ```
> ERROR   - platform_filter - unrecognized platform - qemu_xtensa_mmu
> ```
> 
> It looks like the `qemu_xtensa_mmu` platform, which is required by the SDK CI, has been either renamed or removed from Zephyr. I will look into fixing this.

That should have been updated in https://github.com/zephyrproject-rtos/sdk-ng/pull/708.

**Comment by dbaluta** [comment]
@dcpleung  @keith-packard any idea if this is a legit failure?

```
Run # Activate Python virtual environment
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.4.0-2888-g755bdf80c696
INFO    - Using 'zephyr' toolchain.
ERROR   - platform_filter - unrecognized platform - qemu_xtensa_mmu
ZEPHYR_BASE unset, using "/__w/sdk-ng/sdk-ng/zephyrproject/zephyr"
Error: Process completed with exit code 2.

```

**Comment by dbaluta** [comment]
@dcpleung I really don't understand the problem.

So, Zephyr renamed `qemu_xtensa_dc233c` to `qemu_xtensa_mmu ` but we get an error that `qemu_xtensa_mmu` is not a recognized platform.

**Comment by iuliana-prodan** [comment]
> @stephanosio @dcpleung @nashif @dbaluta I've created a test PR (#715) in which I reverted [1068dfb](https://github.com/zephyrproject-rtos/sdk-ng/commit/1068dfbec483a786942ab5b006c5908d656c8267) hoping to get an error like: `unrecognized platform - qemu_xtensa_dc233c`. But no, I'm getting the same `unrecognized platform - qemu_xtensa_mmu` - see https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/6798463782/job/18487083028?pr=715
> 
> Also, I see the zephyr version is `Zephyr version: zephyr-v3.4.0-2888-g755bdf80c696` - isn't this a bit old, I believe this commit [zephyrproject-rtos/zephyr@1c0178a](https://github.com/zephyrproject-rtos/zephyr/commit/1c0178ae6e00cc0a4744f6217c24c6cfb84cff69) is from 3.5.

I've updated PR https://github.com/zephyrproject-rtos/sdk-ng/pull/715 to use main branch for zephyr (see 2nd commit [here](https://github.com/zephyrproject-rtos/sdk-ng/pull/715/commits/883a2a10f67a42472d0232bbbd30777a3e17f0ea)) but I get the same error and the same zephyr version:

image

So... I'm out of ideas :(
What am I doing wrong?

**Review by tejlmand — APPROVED** [review]

**Comment by stephanosio** [comment]
Rebased to fix CI issues.

**Comment by iuliana-prodan** [comment]
Thank you very much for your help @stephanosio.
The error in the CI - `ERROR   - platform_filter - unrecognized platform - nxp_adsp_imx8ulp` might be to the fact that the Zephyr support for 8ulp is not yet merged  -see https://github.com/zephyrproject-rtos/zephyr/pull/63751?

**Comment by stephanosio** [comment]
> Thank you very much for your help @stephanosio. The error in the CI - `ERROR - platform_filter - unrecognized platform - nxp_adsp_imx8ulp` might be to the fact that the Zephyr support for 8ulp is not yet merged -see [zephyrproject-rtos/zephyr#63751](https://github.com/zephyrproject-rtos/zephyr/pull/63751)?

@iuliana-prodan Yes. I have just pushed a commit to disable the testing of that platform now.

**Comment by dbaluta** [comment]
Thanks a lot @stephanosio  !!

**Pull request merged**
