### PR TITLE
qemu: bump to 4.0.0 release

### PR DESCRIPTION
**Pull request by galak**
Updated nios2 patch to build with qemu 4.0.0

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by ioannisg** [comment]
@galak I am wondering: is there more we need to do, to move to 4.0.0 qemu release?

**Comment by galak** [comment]
> @galak I am wondering: is there more we need to do, to move to 4.0.0 qemu release?

We need to test this in CI to see how it works.

**Comment by ioannisg** [comment]
> 
> 
> > @galak I am wondering: is there more we need to do, to move to 4.0.0 qemu release?
> 
> We need to test this in CI to see how it works.

How will we do that? Do we have a standard process, @galak ?

**Comment by ioannisg** [comment]
I can report, that I managed to run the kernel, and user-mode test suite on qemu4 (an521) with just a couple of tests failing. I am investigating these failures at the moment.

**Comment by galak** [comment]
> How will we do that? Do we have a standard process, @galak ?

We don't have a standard process.  One way is to do it locally, shouldn't be too bad to get a new SDK build and run/test all the QEMU targets against it.

**Pull request merged**
