### PR TITLE
picolibc: Update to picolibc-1.8.7

### PR DESCRIPTION
**Pull request by keith-packard**
Integrate new upstream version.
Include strnlen_s fix.
Include aarch64 cmake fix.

### CODE REVIEW

**Comment by keith-packard** [comment]
Looks like there's some issue running 'node' on the linux CI machines?
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

**Comment by stephanosio** [comment]
> Looks like there's some issue running 'node' on the linux CI machines?
> 
> ```
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
> ```

Yes, this was just fixed.

Regarding other failures, please try rebasing onto the latest main.

**Comment by stephanosio** [comment]
Rebased onto the latest main to pull in the CI fixes.

**Comment by keith-packard** [comment]
Added a picolibc fix for i386 with non-Linux toolchains (like Zephyr). We'll see if that helps?

**Comment by stephanosio** [comment]
```
/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/lib/libc/picolibc/libc-hooks.c:51:34: error: implicit declaration of function 'FDEV_SETUP_STREAM' [-Werror=implicit-function-declaration]
   51 | static LIBC_DATA FILE __stdout = FDEV_SETUP_STREAM(picolibc_put, NULL, NULL, 0);
      |                                  ^~~~~~~~~~~~~~~~~
```

@keith-packard FYI

**Comment by keith-packard** [comment]
> ```
> /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/lib/libc/picolibc/libc-hooks.c:51:34: error: implicit declaration of function 'FDEV_SETUP_STREAM' [-Werror=implicit-function-declaration]
>    51 | static LIBC_DATA FILE __stdout = FDEV_SETUP_STREAM(picolibc_put, NULL, NULL, 0);
>       |                                  ^~~~~~~~~~~~~~~~~
> ```
> 
> @keith-packard FYI

What Zephyr version is this trying to build?

**Comment by stephanosio** [comment]
> What Zephyr version is this trying to build?

https://github.com/zephyrproject-rtos/zephyr/tree/collab-sdk-dev

> Can I get any of the built toolchain artifacts to test against?

You should be able to download one from https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/10938020345?pr=781.

**Comment by keith-packard** [comment]
Managed to reproduce the issue. It looks like the include path is busted -- the picolibc stdio.h isn't getting found; instead it loads the sys-include/stdio.h file which is a hacked up version of the newlib stdio.h file. I'll poke a bit more.

**Comment by keith-packard** [comment]
Yeah, https://github.com/picolibc/picolibc/commit/cf914a3a79578bc97d80c3d3a0090b2fab0eb834 was supposed to fix some bad path handling and appears to have broken the SDK build. I'm not entirely sure what is wrong, but reverting that "should" fix the issue. I'll give that a shot.

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
> Yeah, [picolibc/picolibc@cf914a3](https://github.com/picolibc/picolibc/commit/cf914a3a79578bc97d80c3d3a0090b2fab0eb834) was supposed to fix some bad path handling and appears to have broken the SDK build. I'm not entirely sure what is wrong, but reverting that "should" fix the issue. I'll give that a shot.

That seems to have fixed the issue. Thanks!

**Comment by keith-packard** [comment]
The contributor who provided https://github.com/picolibc/picolibc/commit/cf914a3a79578bc97d80c3d3a0090b2fab0eb834 has provided an updated version which should work for Zephyr in my next picolibc update (which looks like it might be soon; there are a bunch of small fixes which 1.8.7 provoked that would be nice to have in a 'real' picolibc release, synchronized with Zephyr).

**Pull request merged**
