### PR TITLE
qemu: Bump to v5.0.0

### PR DESCRIPTION
**Pull request by stephanosio**
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

### CODE REVIEW

**Comment by stephanosio** [comment]
`nios2-softmmu` seems to be broken on QEMU 5.0 (building on `v5.2.0-rc2` tag):
```
  LINK    nios2-softmmu/qemu-system-nios2
hw/nios2/boot.o: In function `nios2_load_dtb':
/home/stephanos/Dev/qemu/hw/nios2/boot.c:89: undefined reference to `load_device_tree'
/home/stephanos/Dev/qemu/hw/nios2/boot.c:96: undefined reference to `qemu_fdt_setprop_string'
/home/stephanos/Dev/qemu/hw/nios2/boot.c:104: undefined reference to `qemu_fdt_setprop_cell'
/home/stephanos/Dev/qemu/hw/nios2/boot.c:107: undefined reference to `qemu_fdt_setprop_cell'
collect2: error: ld returned 1 exit status
Makefile:208: recipe for target 'qemu-system-nios2' failed
make[1]: *** [qemu-system-nios2] Error 1
Makefile:527: recipe for target 'nios2-softmmu/all' failed
make: *** [nios2-softmmu/all] Error 2
```

**Comment by stephanosio** [comment]
> `nios2-softmmu` seems to be broken on QEMU 5.0

The following commit is the culprit, although not the root cause:
https://github.com/qemu/qemu/commit/7ba4a4d328a1341e49773c66eda9baa19c503b96

I will prepare/upstream a patch for this.

**Comment by stephanosio** [comment]
All QEMU 5.0-related issues have been resolved. Ready for final review/merging.

**Comment by stephanosio** [comment]
To be updated to the v5.0.0 release, which is due today.

**Comment by stephanosio** [comment]
Updated to QEMU 5.0.0

**Comment by stephanosio** [comment]
NOTE: Need to do something about the newly added massive ARC patch ...

**Comment by galak** [comment]
@abrodkin are you able to look at updating the ARC changes to be based on QEMU 5.0.0?

**Comment by abrodkin** [comment]
@galak in fact it was done a week ago already, see https://github.com/stephanosio/zephyr-qemu/issues/14#issuecomment-635454984
Or just cherry-pick this patch - https://github.com/abrodkin/qemu/commit/d2fb10a24959bcbc53bd543a49cfd3ff3a334670.

Do you want me to submit a patch with patch for meta-zephyr?

**Comment by galak** [comment]
> @galak in fact it was done a week ago already, see [stephanosio/zephyr-qemu#14 (comment)](https://github.com/stephanosio/zephyr-qemu/issues/14#issuecomment-635454984)
> Or just cherry-pick this patch - [abrodkin/qemu@d2fb10a](https://github.com/abrodkin/qemu/commit/d2fb10a24959bcbc53bd543a49cfd3ff3a334670).
> 
> Do you want me to submit a patch with patch for meta-zephyr?

If you can submit a patch that would be great, might need to be based on this PR.

**Comment by abrodkin** [comment]
@galak Ok I'll try to do it now. How soon this is needed?

**Comment by galak** [comment]
> @galak Ok I'll try to do it now. How soon this is needed?

Not urgent, but in the next week or so?  Trying to make some progress on these open PRs.

**Comment by abrodkin** [comment]
@galak I tried to use Docker container (https://hub.docker.com/r/crops/poky-zephyr-sdk/) as it's suggested here https://github.com/zephyrproject-rtos/sdk-ng/tree/master/meta-zephyr-sdk but see this:
```
$ bitbake zephyr-qemu

...

ERROR: zephyr-qemu-git-r0 do_configure: Function failed: do_configure (log file is located at /workdir/build/tmp/work/i586-poky-linux/zephyr-qemu/git-r0/temp/log.do_configure.143864)
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/i586-poky-linux/zephyr-qemu/git-r0/temp/log.do_configure.143864
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_copy_aclocals
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
| DEBUG: Executing shell function do_configure
| 
| ERROR: Cannot use '/usr/bin/python3', Python >= 3.5 is required.
|        Use --python=/path/to/python to specify a supported Python.
```

Is it expected? I guess not :)

**Comment by abrodkin** [comment]
Was able to build `zephyr-qemu` finally with help ofhttps://hub.docker.com/r/crops/poky though :)

See https://github.com/stephanosio/zephyr-sdk-ng/pull/1

**Comment by stephanosio** [comment]
Rebased onto the latest master

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/25100#issuecomment-639222487

**Comment by ioannisg** [comment]
@stephanosio @galak what is the status of this?
Could we merge  this and unblock the work for getting Cortex-M4F into Qemu-supported ARCHes, early in the 2.4 release?

**Comment by stephanosio** [comment]
> @stephanosio @galak what is the status of this?
> Could we merge this and unblock the work for getting Cortex-M4F into Qemu-supported ARCHes, early in the 2.4 release?

@ioannisg This PR in itself is ready for merging. The rest is up to @galak :)

**Comment by ioannisg** [comment]
> > @stephanosio @galak what is the status of this?
> > Could we merge this and unblock the work for getting Cortex-M4F into Qemu-supported ARCHes, early in the 2.4 release?
> 
> @ioannisg This PR in itself is ready for merging. The rest is up to @galak :)

Hm, interesting :) Then I can merge it myself, perhaps? 🥇

**Comment by stephanosio** [comment]
> Hm, interesting :) Then I can merge it myself, perhaps? 🥇

There have been some subtle/minor changes that potentially warrant 0.11.4 release (e.g. cd1657df97b21b34c7051211dac3132b9ef3e67d). I think that is one thing holding up this PR.

@galak seems to be working on a new CI (that is, hopefully, able to handle different branches) for sdk-ng now, so we should be able to get this PR in without worrying about 0.11.x release soon enough.

**Comment by galak** [comment]
> > Hm, interesting :) Then I can merge it myself, perhaps? 🥇
> 
> There have been some subtle/minor changes that potentially warrant 0.11.4 release (e.g. [cd1657d](https://github.com/zephyrproject-rtos/sdk-ng/commit/cd1657df97b21b34c7051211dac3132b9ef3e67d)). I think that is one thing holding up this PR.
> 
> @galak seems to be working on a new CI (that is, hopefully, able to handle different branches) for sdk-ng now, so we should be able to get this PR in without worrying about 0.11.x release soon enough.

Happy to merge this if someone will take the test build of the SDK and make sure all the qemu platforms still pass and report the results here.

**Comment by abrodkin** [comment]
> 
> 
> > > Hm, interesting :) Then I can merge it myself, perhaps? 🥇
> > 
> > 
> > There have been some subtle/minor changes that potentially warrant 0.11.4 release (e.g. [cd1657d](https://github.com/zephyrproject-rtos/sdk-ng/commit/cd1657df97b21b34c7051211dac3132b9ef3e67d)). I think that is one thing holding up this PR.
> > @galak seems to be working on a new CI (that is, hopefully, able to handle different branches) for sdk-ng now, so we should be able to get this PR in without worrying about 0.11.x release soon enough.
> 
> Happy to merge this if someone will take the test build of the SDK and make sure all the qemu platforms still pass and report the results here.

I may give it a spin. Do we have a full list of QEMU platforms to run test for?

**Comment by galak** [comment]
> I may give it a spin. Do we have a full list of QEMU platforms to run test for?

```
[galak@spiff zephyr]$ git grep EMU_PLATFORM | grep qemu
boards/arc/qemu_arc/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/mps2_an385/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/mps2_an521/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/qemu_cortex_a53/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/qemu_cortex_m0/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/qemu_cortex_m3/board.cmake:set(EMU_PLATFORM qemu)
boards/arm/qemu_cortex_r5/board.cmake:set(EMU_PLATFORM qemu)
boards/nios2/qemu_nios2/board.cmake:set(EMU_PLATFORM qemu)
boards/riscv/hifive1/board.cmake:set(EMU_PLATFORM qemu)
boards/riscv/qemu_riscv32/board.cmake:set(EMU_PLATFORM qemu)
boards/riscv/qemu_riscv64/board.cmake:set(EMU_PLATFORM qemu)
boards/x86/qemu_x86/board.cmake:set(EMU_PLATFORM qemu)
boards/xtensa/qemu_xtensa/board.cmake:set(EMU_PLATFORM qemu)
```

**Comment by abrodkin** [comment]
> 
> 
> > I may give it a spin. Do we have a full list of QEMU platforms to run test for?
> 
> ```
> [galak@spiff zephyr]$ git grep EMU_PLATFORM | grep qemu
> boards/arc/qemu_arc/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/mps2_an385/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/mps2_an521/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/qemu_cortex_a53/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/qemu_cortex_m0/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/qemu_cortex_m3/board.cmake:set(EMU_PLATFORM qemu)
> boards/arm/qemu_cortex_r5/board.cmake:set(EMU_PLATFORM qemu)
> boards/nios2/qemu_nios2/board.cmake:set(EMU_PLATFORM qemu)
> boards/riscv/hifive1/board.cmake:set(EMU_PLATFORM qemu)
> boards/riscv/qemu_riscv32/board.cmake:set(EMU_PLATFORM qemu)
> boards/riscv/qemu_riscv64/board.cmake:set(EMU_PLATFORM qemu)
> boards/x86/qemu_x86/board.cmake:set(EMU_PLATFORM qemu)
> boards/xtensa/qemu_xtensa/board.cmake:set(EMU_PLATFORM qemu)
> ```

May I safely guess those platforms except `qemu_arc` are mapped 1-to-1 to a "platfrom" used for execution? I.e. `qemu_cortex_a53` doesn't hide `qemu_cortex_a53_XX` & `qemu_cortex_a53_YY`, right? I guess `qemu_x86` & `qemu_x86_64` are an another example?

Is there a way to just run all QEMU-based boards at once?

**Comment by stephanosio** [comment]
> Is there a way to just run all QEMU-based boards at once?

In theory, filtering by `CONFIG_QEMU_TARGET=y` should work, but it doesn't seem like all QEMU "boards" set this.

Maybe @nashif has a better idea.

**Comment by stephanosio** [comment]
@galak https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/75640/summary/console

That ran with [zephyr-qemu](https://github.com/stephanosio/zephyr-qemu), which is based on QEMU v5.0.0 and, for all practical purposes, equivalent to what is in this PR.

As you can see, all tests pass (ignore the two failures that do not have anything to do with QEMU).

**Comment by stephanosio** [comment]
@galak Shall we merge this now?

**Pull request merged**
