### PR TITLE
xtensa: Add xtensa-amd_acp_6_0_adsp_zephyr-elf

### PR DESCRIPTION
**Pull request by DINESHKUMARK1**
This adds the config and overlay files to enable building the toolchain needed for the acp_6_0 board in Zephyr.

### CODE REVIEW

**Comment by DINESHKUMARK1** [comment]
@stephanosio,  Could you please review the pull request? There are CI test failures and it seems they are expected as mentioned in
https://github.com/zephyrproject-rtos/sdk-ng/pull/778#pullrequestreview-2300097185
. Please let me know if anything needs to be taken care from side.

**Comment by DINESHKUMARK1** [comment]
@stephanosio, Could you please review the pull request?  Please let me know if anything needs to be taken care from side.

**Comment by stephanosio** [comment]
> @stephanosio, Could you please review the pull request? Please let me know if anything needs to be taken care from side.

@DINESHKUMARK1 I have created and pushed the changes in this PR to the upstream `topic-amd_acp_6_0` branch so that the CI workflow changes can be tested.

I have also invited you as a collaborator to this repository, and you should be able to directly push to `topic-amd_acp_6_0` branch if you need to make any further changes.

Superseded by https://github.com/zephyrproject-rtos/sdk-ng/pull/792.

**Comment by stephanosio** [comment]
@DINESHKUMARK1 I have modified the commit in the topic branch to fix obvious errors in the CI workflow changes; but, it looks like there is more to fix than that:

```
Error:     ../gnulib/import/wchar.h:747:1: error: expected ',' or '...' before 'pwc'
Error:     /__w/_temp/workspace/build/.build/xtensa-amd_acp_6_0_adsp_zephyr-elf/src/gdb/gdb/../gdbsupport/gdb_vecs.h:27:20: error: 'gdb' was not declared in this scope
Error:     /__w/_temp/workspace/build/.build/xtensa-amd_acp_6_0_adsp_zephyr-elf/src/gdb/gdb/../gdbsupport/gdb_vecs.h:27:48: error: template argument 1 is invalid
Error:     /__w/_temp/workspace/build/.build/xtensa-amd_acp_6_0_adsp_zephyr-elf/src/gdb/gdb/../gdbsupport/gdb_vecs.h:27:48: error: template argument 2 is invalid
...
```

https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/10944341634/job/30385967408#step:13:345

**Pull request closed without merging**
