### PR TITLE
Revert "gdb: Build gdb static" as it disables python support

### PR DESCRIPTION
**Pull request by galak**
The attempt to build python statically was to address an issue with
python library being needed, however this ends up breaking python
support so lets revert the commit and we'll document the need to have
python3.6.

This reverts commit 6ad840ac76b699a4abf54fe08145b0b1986471ce.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
Need to add a doc update for this.

**Comment by carlescufi** [comment]
cc @joerchan

**Comment by joerchan** [comment]
Thank you!

**Comment by galak** [comment]
Documenting this here:

On fedora if python3.6 isn't installed we get:

```
arm-zephyr-eabi-gdb: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

fixed by `sudo dnf install python36`

**Pull request merged**
