### PR TITLE
Update newlib to v3.3 + zephyr + xtensa patches

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@dcpleung can you look at the failure on x86_64 build w/newlib-3.3:

https://buildkite.com/zephyr/sdk-ng/builds/123#ec5651a1-edb6-479e-91e9-b7de20b8c780

**Comment by dcpleung** [comment]
Given the error message, it seems like newlib is using the wrong machine directory (using `machine/x86_64` instead of `machine/i386` for building 32-bit libraries).

**Comment by dcpleung** [comment]
Your latest update to add `CT_EXPERIMENTAL=y` should work. Without it, crosstool-ng reverts to using 3.1 tarball, and not using the git repo.

**Comment by galak** [comment]
> Your latest update to add `CT_EXPERIMENTAL=y` should work. Without it, crosstool-ng reverts to using 3.1 tarball, and not using the git repo.

Thanks, made that update and running through CI now.

**Comment by dcpleung** [comment]
I just built `x86_64-zephyr-elf` locally and it worked after adding `CT_EXPERIMENTAL`.

Just one thing, the newlib repo is missing the patch from commit commit f73e8b57e00edcd9b5ef24b153c554c99aa68b23
(`x86_64: newlib: use march=pentium for 32-bit`). This one is needed for 32-bit x86.

**Comment by galak** [comment]
> I just built `x86_64-zephyr-elf` locally and it worked after adding `CT_EXPERIMENTAL`.
> 
> Just one thing, the newlib repo is missing the patch from commit commit [f73e8b5](https://github.com/zephyrproject-rtos/sdk-ng/commit/f73e8b57e00edcd9b5ef24b153c554c99aa68b23)
> (`x86_64: newlib: use march=pentium for 32-bit`). This one is needed for 32-bit x86.

Hmm, when we added the mach=pentium fix, did we break commit df84499eba3fb1c97592506a19d060113b64483d?

**Comment by galak** [comment]
@dcpleung would appreciate your testing on xtensa with this PR.  I think this should supersede #257.   Has the nicety of now unifying the xtensa newlib with all other arch's.

**Comment by dcpleung** [comment]
> @dcpleung would appreciate your testing on xtensa with this PR. I think this should supersede #257. Has the nicety of now unifying the xtensa newlib with all other arch's.

Do you have a link to the built toolchain?

**Comment by galak** [comment]
> Do you have a link to the built toolchain?

builds.zephyrproject.org/zephyrproject-rtos/sdk-ng/258/zephyr-sdk-0.11.4-pr-258-x86_64-linux-setup.run

**Comment by dcpleung** [comment]
I have run the new SDK again `intel_s1000_crb` and `up_squared_adsp` on a few apps, since I don't have the setup to do automatic sanitycheck. I explicitly tested `tests/application_development/libcxx` and the kernel `*_api` tests. Apps that worked before continue working, and broken ones are still broken. So I think this is good to go in terms of Xtensa.

**Pull request merged**
