### PR TITLE
xtensa: remove unused intel_bdw and intel_byt

### PR DESCRIPTION
**Pull request by dcpleung**
Both intel_bdw and intel_byt are not being used in upstream Zephyr project. So there is no need to build them.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Comment by dcpleung** [comment]
Quick grep on Zephyr main repo says that these are never used.

**Comment by stephanosio** [comment]
cc @marc-hb

**Review by marc-hb — APPROVED** [review]
cc: @lgirdwood , @plbossart, @mengdonglin, @kv2019i , @fredoh9, @aichaosong, @keqiaozhang

**Comment by galak** [comment]
@dcpleung was thinking about this the other day and was going to ask if we still needed them :).

**Comment by lgirdwood** [comment]
Not needed. Can be removed.

**Review by lgirdwood — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by stephanosio** [comment]
@dcpleung There are merge conflicts. Could you rebase?

**Review by aiChaoSONG — APPROVED** [review]
SOF Jenkins CI never uses the toolchain to build bdw/byt/cht, so should be good.

**Comment by lgirdwood** [comment]
@dcpleung looks like the GH action will need an update too in order to remove the check for the removed platforms.

**Comment by dcpleung** [comment]
Rebased. Picolib has GitHub actions on BDW and BYT so those need to be removed too.

**Comment by dcpleung** [comment]
Picolibc PR: https://github.com/picolibc/picolibc/pull/391

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
